baseURL = "https://karpet.bangunan.co/"
languageCode = "id"
title = "Grosir Karpet | Grosir Karpet Masjid dan Musholla Murah"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Karpet Masjid dan Musholla - Grosir Karpet Berkualitas dengan Harga Murah dan Gratis Pemasangan"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual karpet masjid", "karpet musholla", "karpet masjid murah", "grosir karpet", "karpet masjid tebal", "distributor karpet masjid", "karpet sajadah", "karpet masjid premium"]
  base_price = 100000
  price_range = 50000
  free_shipping = true
  materials = [
  "Karpet Masjid Polos",
  "Karpet Musholla Motif",
  "Karpet Masjid Tebal",
  "Karpet Musholla Anti-Slip",
  "Karpet Masjid Premium",
  "Karpet Musholla Ekonomis"
  ]
  categories = ["Karpet Masjid", "Karpet Musholla", "Karpet Sajadah", "Karpet Premium"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk barang dengan cacat produksi.",
  "Barang yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Grosir Karpet Masjid dan Musholla"
  hero_description = "Kami menawarkan berbagai pilihan karpet berkualitas untuk masjid dan musholla dengan desain elegan serta bahan yang nyaman dan tahan lama. Solusi terbaik untuk mempercantik interior tempat ibadah Anda dengan harga grosir yang terjangkau."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Karpet"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan karpet masjid dan musholla dengan berbagai desain, bahan berkualitas, dan harga grosir yang kompetitif. Layanan pengiriman free ongkir juga konsultasi gratis juga tersedia untuk membantu Anda memilih karpet yang sesuai dengan kebutuhan tempat ibadah Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "Karpet.bangunan.co menawarkan berbagai pilihan karpet masjid dan musholla dengan desain elegan serta bahan yang nyaman dan tahan lama. Kami mengutamakan kepuasan pelanggan dengan karpet yang estetis dan fungsional. Pilih kami untuk melengkapi tempat ibadah Anda dengan karpet berkualitas."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Rudi|Hendra|Agus|Wawan|Fajar|Rio}"
  message = "{Saya membeli karpet dari karpet.bangunan.co untuk {musholla|ruang ibadah} di rumah saya, dan hasilnya {sangat memuaskan|luar biasa}. {Kualitas|Mutu} karpet {sangat bagus|berkualitas tinggi|unggul} dan {nyaman|lembut}.|Karpet yang saya pesan dari karpet.bangunan.co {sangat nyaman|lembut} dan {sesuai|cocok} dengan desain rumah saya.}"
  response = "{Terima kasih atas kepercayaannya! Kami senang dapat menyediakan karpet {berkualitas|unggul} untuk {musholla|ruang ibadah} Anda.|Kami menghargai kepercayaan Anda. Terima kasih telah memilih karpet kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Fitri|Lina|Diah|Maya|Nur}"
  message = "{karpet.bangunan.co {sangat membantu|mempermudah} dalam memilih karpet untuk {masjid|musholla} kami. Karpet yang kami {pilih|beli} {sangat nyaman|lembut} dan {menambah kesan indah|mempercantik} di {ruang ibadah|area sholat}.|Saya {puas|senang} dengan layanan karpet.bangunan.co, karpetnya {berkualitas|nyaman} dan membuat ruang ibadah lebih {indah|nyaman}.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan karpet yang kami sediakan.|Terima kasih atas kepercayaan Anda. Kami senang dapat membantu memperindah ruang ibadah Anda!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Galih|Rizal|Bambang|Faisal|Ali|Toni|Deni}"
  message = "{Karpet dari karpet.bangunan.co {sangat elegan|berkualitas} dan {cocok|tepat} untuk musholla di rumah saya. Proses {pembelian|order} dan {pengirimannya|pengantaran} juga {sangat cepat|efisien}.|Karpet dari karpet.bangunan.co {berkualitas|nyaman} dan sesuai dengan kebutuhan musholla rumah saya. Pengirimannya juga {lancar|cepat}.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan karpet {berkualitas|elegan} dan sesuai dengan kebutuhan Anda.|Kami senang bisa memenuhi harapan Anda. Terima kasih atas ulasannya!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Deni|Hendra|Toni|Wawan|Gilang|Ari|Benny|Yudi}"
  message = "{Saya {sangat puas|senang|terkesan} dengan karpet dari karpet.bangunan.co. Karpetnya {sangat nyaman|empuk} dan sesuai dengan desain {minimalis|modern} musholla saya.|Karpet yang saya pesan dari karpet.bangunan.co {sangat cocok|tepat} dengan desain musholla saya dan {sangat nyaman|empuk}.}"
  response = "{Senang mendengar Anda puas dengan produk kami, {Andi|Eko}. Terima kasih atas kepercayaannya!|Kami sangat menghargai kepercayaan Anda. Terima kasih telah memilih produk kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan karpet.bangunan.co {sangat memuaskan|luar biasa}. Karpet yang saya {pasang|beli} di musholla kantor {sangat berkualitas|kokoh} dan sesuai dengan {harapan|ekspektasi} saya.|Saya {sangat puas|terkesan} dengan karpet dari karpet.bangunan.co, kualitas dan kenyamanannya {luar biasa|hebat}.}"
  response = "{Terima kasih! Kami senang dapat membantu memperindah musholla kantor Anda dengan karpet {berkualitas|unggul}.|Kami sangat menghargai ulasan Anda. Terima kasih atas kepercayaannya!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Rio|Galih|Faisal|Yanto|Benny|Toni|Deni|Rizal|Wawan}"
  message = "{Karpet dari karpet.bangunan.co {sangat sesuai|tepat} dengan desain musholla di rumah saya. Pengirimannya {cepat|aman|lancar} dan karpet {sangat nyaman|empuk}.|Saya {puas|terkesan} dengan karpet dari karpet.bangunan.co, {nyaman|lembut} dan sesuai dengan desain musholla saya.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan produk karpet kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan musholla Anda kepada kami. Kami senang Anda puas dengan hasilnya.}"
  rating = 4

[[params.tabelItems]]
  name = "Karpet Masjid Polos"
  price = "200.000 /m"
[[params.tabelItems]]
  name = "Karpet Musholla Motif"
  price = "250.000 /m"
[[params.tabelItems]]
  name = "Karpet Masjid Tebal"
  price = "300.000 /m"
[[params.tabelItems]]
  name = "Karpet Musholla Anti-Slip"
  price = "150.000 /m"
[[params.tabelItems]]
  name = "Karpet Masjid Premium"
  price = "350.000 /m"
[[params.tabelItems]]
  name = "Karpet Musholla Ekonomis"
  price = "65.000 /m"

[params.appliList]
  "Karpet Masjid Polos" = "masjid besar, aula shalat"
  "Karpet Musholla Motif" = "musholla kecil, ruang ibadah pribadi"
  "Karpet Masjid Tebal" = "masjid utama, ruang ibadah besar"
  "Karpet Musholla Anti-Slip" = "musholla anak-anak, ruangan dengan risiko licin"
  "Karpet Masjid Premium" = "masjid megah, ruang ibadah dengan desain mewah"
  "Karpet Musholla Ekonomis" = "musholla kecil, anggaran terbatas"

[params.kegunaanList]
  "Karpet Masjid Polos" = "cocok untuk masjid besar dengan tampilan elegan"
  "Karpet Musholla Motif" = "memperindah musholla dengan motif yang menarik"
  "Karpet Masjid Tebal" = "nyaman untuk ibadah dalam masjid besar dengan ketebalan ekstra"
  "Karpet Musholla Anti-Slip" = "melindungi dari risiko tergelincir pada permukaan licin"
  "Karpet Masjid Premium" = "menambah kesan mewah di masjid dengan kualitas premium"
  "Karpet Musholla Ekonomis" = "pilihan terbaik untuk musholla dengan anggaran terbatas"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Grosir Karpet Masjid & Musholla Berkualitas | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"